# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2be8735c8677ee74c27e3b9ecad9763cd573118933914da84a92aeb360f3b3263489e2a6d248f628cd910cfab4660b9b734cd75c87112361a4825be67a122c51

test:
  secret_key_base: 3ea2e9dbacf923da4f19914d85a18eeac0b1acadba6ef0e1fec9661858bce656ccd41598cb76badd6bfed64ddfbc7825ca749b00a20ff6190e986967fb353b1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
